#!/usr/bin/env python3

# program description: calculates the current moon phase.

# inspired by: https://gist.github.com/Crysknife007/29b00826c86b9a91945ce6e4efccc2b5
# inspired by: https://gist.github.com/miklb/ed145757971096565723

import math, decimal, datetime
dec = decimal.Decimal

def main():
   now       = datetime.datetime.now()
   diff      = now - datetime.datetime(2001, 1, 1)
   days      = dec(diff.days) + (dec(diff.seconds) / dec(86400))
   lunations = dec("0.20439731") + (days * dec("0.03386319269"))
   pos       = lunations % dec(1)
   index     = (pos * dec(8)) + dec("0.5")
   index     = math.floor(index)
   phasename = {
      0: "○ New Moon",
      1: "❩ Waxing Crescent",
      2: "◗ First Quarter",
      3: "◑ Waxing Gibbous",
      4: "● Full Moon",
      5: "◐ Waning Gibbous",
      6: "◖ Last Quarter",
      7: "❨ Waning Crescent"
   }[int(index) & 7]
   roundedpos = round(float(pos), 3)
   print(f'lunar phase:   {phasename}')
   print(f'moon position: {roundedpos}')

if __name__=="__main__":
   main()
